# Generated by Django 5.2 on 2025-06-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('reviewed_by_shraiya', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('author_id', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('category_id', models.IntegerField()),
                ('book_link', models.URLField()),
                ('content', models.TextField()),
            ],
        ),
    ]
