# Generated by Django 5.2.3 on 2025-06-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_scraped',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
