# Generated by Django 5.2 on 2025-06-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_appuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reviewed_by_shraiya',
            field=models.BooleanField(default=False),
        ),
    ]
