# Generated by Django 5.2 on 2025-06-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_appuser_created_at_appuser_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
