# Generated by Django 5.2 on 2025-06-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_appuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
