# Generated by Django 5.2 on 2025-06-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_is_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_link',
            field=models.CharField(max_length=500),
        ),
    ]
